### ISSUE TITLE
Composants : ajouter les heures

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/api#10]
Aucune difficulté, les heures sont standalone. Toute la pile du composant est à créer, sans recherche particulière (à ma connaissance)

**Comment by wouldsmina** [comment]
j'essaye de commencer un début de quelque chose mais je sais pas trop quel arborescence adopter :/
dis moi ce que tu dis de ça : 
Employes/
Responsable/
Gestionnaire/ (ouais, j'aime pas RH on sais pas trop ce que ça veut dire...)

du coup comment sont géré les profiles (comment je sais que l'utilisateur qui fait une requête a les droits)? 

(et je me demande aussi si je ne devrais pas commencer par faire la doc...)

**Comment by Prytoegrian** [comment]
> du coup comment sont gérés les profiles (comment je sais que l'utilisateur qui fait une requête a les droits)?

Pour le moment, il n'a pas de gestion des droits ; c'est la thématique du token que je fais en ce moment qui va s'en occuper. Pour le moment, si tu peux forger la requête, tu as accès aux heures.

(Gestionnaire me plaît bien, mais on sait pas non plus ce que ça veut dire ^^)

Comme tu me l'as détaillé par IRC, ça me paraît bon comme ceci : 
- App/Components/Employe/{id}/Heure/Additionnelle || Repos

On peut commencer par chercher à avoir les heures d'un employé donné. Pas d'ajout, ni de modif, juste de la lecture. Par la suite on pourrait mettre les ajouts ; le responsable, lui,  pourrait avoir : 
- App/Components/Responsable/{id}/Heure/Additionnelle || Repos
pour voir la liste de tout ce qui a en gestion + pour valider des demandes

---
Le problème pour le moment, c'est qu'on a pas la gestion des droits, donc tu peux pas trouver l'id de l'employé courant, donc soit : 
- tu mets tout à plat : App/Components/Heure/Add et on modifiera plus tard,
- tu mets les urls que j'ai évoquées et l'id n'a pas (encore) d'importance, 
- tu gères les droits au préalable.


Si les évolutions nous montrent qu'on se trompe, comme tout est testable, on changera de voie :smile_cat:

**Comment by prytoegrian** [comment]
Je me colle aux heures de l'utilisateur.

**Comment by prytoegrian** [comment]
* [ ] Il ne reste plus qu'à faire les heures additionnelles. Celui qui voudra tenter sa chance peut s'amuser à suivre https://github.com/libertempo/api/pull/94

:warning: Il y a un petit travail de design, ça peut être sympa à faire.

**Comment by wouldsmina** [comment]
je vais me laisser tenter! ;)
