### ISSUE TITLE
LDAP KO

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/api#111]
Hi. Apparemment LDAP est KO, mais je ne remarque rien de particulier. La dernière PR a avoir touché à ça est https://github.com/libertempo/api/pull/74. Si t'as plus d'info, je prends.

**Comment by wouldsmina** [comment]
Salut. Depuis LT 1.13 les dépendances sont installé depuis composer, si tu compares le fichier  vendor/libertempo/api/Tools/Services/LdapAuthentifierService.php tiré de composer avec celui [du dépot github](https://github.com/libertempo/api/blob/master/Tools/Services/LdapAuthentifierService.php) tu pourras constater qu'il manque justement #74.

**Comment by wouldsmina** [comment]
En fait, c'est la version [1.7](https://github.com/libertempo/api/blob/v1.7.0/Tools/Services/LdapAuthentifierService.php) qui est diffusée par composer. 
#74 est arrivé à partir de la [1.8](https://github.com/libertempo/api/blob/v1.8.0/Tools/Services/LdapAuthentifierService.php)

**Comment by prytoegrian** [comment]
OK, je comprends mieux ce qu'il se passe.
Le fait est que l'API est très en retard vis à vis du cycle de vie web ; ça fait quelques temps que ça me taraude, j'aimerais tenter une piste mais faut que je formalise la méthodo et j'ai d'autres choses dans les tuyaux actuellement.

Là, il nous est possible de faire une version "patch" de web v1.13.1 pour monter la version de l'API. Cette dernière suit semver donc on est sûr qu'il n'y a pas de rupture de compat' entre 1.7 et les 1.* supérieures. C'est l'action minimale nécessaire et suffisante pour corriger ce ticket.

**Comment by wouldsmina** [comment]
ça roule! je prépare un PR sur web :+1:

**Comment by prytoegrian** [comment]
Peut-on clore ?

**Comment by wouldsmina** [comment]
Ah bah oui ! ;)

**Comment by prytoegrian** [comment]
\o/
