### ISSUE TITLE
route /utilisateur/ à limiter aux HR

### ISSUE THREAD

**Issue by wouldsmina** [libertempo/api#114]
la route /utilisateur/ retourne tous les utilisateurs, elle ne devrait être accessible que par le HR. Je propose de retourner seulement les datas de l'utilisateur en cours lors d'une requête sur /employe/me. Tu en penses quoi @prytoegrian ? 

Idem pour /absence/periode à remplacer par /employe/me/absence/periode.

**Comment by prytoegrian** [comment]
> la route /utilisateur/ retourne tous les utilisateurs, elle ne devrait être accessible que par le HR. Je propose de retourner seulement les datas de l'utilisateur en cours lors d'une requête sur /employe/me.

:+1: 

> Idem pour /absence/periode à remplacer par /employe/me/absence/periode.

Rappelle-moi qui appelle `/absence/periode` ?

**Comment by wouldsmina** [comment]
> Rappelle-moi qui appelle /absence/periode ?

pour le moment nul part.

**Comment by prytoegrian** [comment]
Hum. Alors autre question : dans quel contexte cette route *est censée* être appelée ? :smile:

**Comment by wouldsmina** [comment]
Pour le HR,
- liste des congés à traiter
- consultation et édition des congés d'un employé
- accessoirement, afficher le nombre de congés à traiter dans une bulle (comme ça l'a été dans une précédente version). C'est d'ailleurs pour ça que je me suis penché dessus.

Je suis pas sûr de répondre à ta question, désolé si je suis à côté.

**Comment by prytoegrian** [comment]
Va pour une restriction au HR !

**Comment by wouldsmina** [comment]
j'étais parti pour créer employe/me dans la foulée, mais je constate un petit problème avec /utilisateur/{id}, id est typé en `integer` alors qu'il correspond actuellement au login. 

@prytoegrian vu que la BDD contient désormais des "vrais" PK, je me demande si tu compte adapter (massivement) l'API en conséquence ? Si c'est le cas, je vais attendre pour créer employe/me.

**Comment by prytoegrian** [comment]
Oui. C'est en cours. Le BPM de #115 va déclencher toute une refonte de la gestion de la BDD. Je ferai les choses en douceur pour assurer une compat' maximale et des PRs réduites.

Ceci étant, si {id} est typecasté en `int`, c'est une erreur pour le moment. Si tu veux avancer, fais ce que tu as à faire, je ferai les correctifs qui s'imposent dans ma branche.

**Comment by wouldsmina** [comment]
je coince sur l'accessChecker :cry: 
`Rights were not configured for the route Utilisateur|Georges`
J'ai tenté le wildcard mais ça passe pas non plus.

Je devrais tout de même pouvoir avancer sur employe/me

**Comment by wouldsmina** [comment]
je bloque à nouveau, cette fois avec l'erreur : 
```
{
  "code": 500,
  "status": "error",
  "message": "Internal Server Error",
  "data": "An exception occurred while executing 'SELECT *, u_login AS id FROM c c,  WHERE u_login = ?' with params [\"pierre\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE u_login = 'pierre'' at line 1"
}
```
J'arrive pas à comprendre... je fais une pause le temps d'y voir plus clair :)

**Comment by prytoegrian** [comment]
```diff
- SELECT *, u_login AS id FROM c c,  WHERE u_login = ?' with params [\"pierre\"]
+ SELECT *, u_login AS id FROM conges_users c  WHERE u_login = ?' with params [\"pierre\"]
```
Il y a une virgule en trop et ton nom de table n'existe pas :-)

**Comment by wouldsmina** [comment]
mais pourquoi ? J'ai fait un truc de travers mais je vois pas ou :(
https://github.com/libertempo/api/compare/ws/employeMe

**Comment by wouldsmina** [comment]
Je suis parti du principe que le repository et l'entitie étaient bons, mais vue que je n'ai pas réussi à tester avec /utilisateur/{id} je vais y jeter un œil quand même.

**Comment by wouldsmina** [comment]
non, je vois pas d’où viens le soucis :/

**Comment by prytoegrian** [comment]
Je vais regarder

**Comment by wouldsmina** [comment]
Tu as pu y jeter un œil ? J'ai tout essayé je reste coincer :(

**Comment by prytoegrian** [comment]
Oups, surcharge de travail au boulot. Je me note de faire ça ce soir.

**Comment by prytoegrian** [comment]
J'ai pas bien compris ce qu'il se passait, mais comme la nouvelle gestion du stockage arrive, je pense qu'on va pas se prendre la tête plus que ça. Avance, je te rattraperai.

En faisant ceci, tu devrais tomber sur tes pattes :

```diff
@ Utilisateur/UtilisateurRepository.php:44 @ class UtilisateurRepository extends \LibertAPI\Tools\Libraries\ARepository

    public function getOne($id) : AEntite
    {
+       // @TODO: supprimer cette ligne quand on passera à DBAL > 2.6 : https://github.com/doctrine/dbal/commit/e937f37a8acc117047ff4ed9aec493a1e3de2195
+       $this->queryBuilder->resetQueryParts();
        $this->queryBuilder->select('*, u_login AS id');
        $this->setWhere(['id' => $id]);
+       $this->queryBuilder->from($this->getTableName(), 'current');
        $res = $this->queryBuilder->execute();

        $data = $res->fetch(\PDO::FETCH_ASSOC);
```

Par contre, prends garde à ne pas supprimer des routes ou des comportements dans tout ce qui est accessible au client. Comme on suit [semver](https://github.com/libertempo/api#versions), il faut assurer un maximum de compatibilité. Je te propose de mettre [ces lignes](https://github.com/libertempo/api/compare/ws/employeMe#diff-196da0c2a5a7819f3fde6b336de75fc4L12-L20) en deprecated plutôt.

**Comment by wouldsmina** [comment]
> Par contre, prends garde à ne pas supprimer des routes ou des comportements dans tout ce qui est accessible au client.

La route supprimée semble n'avoir jamais fonctionné. ça compte quand même ? :innocent:

**Comment by wouldsmina** [comment]
Merci pour le coup de pouce :+1:
