### ISSUE TITLE
[BDD] revue des clés primaire

### ISSUE THREAD

**Issue by wouldsmina** [libertempo/api#21]
Pour la bonne marche du développement de l'API, il devient nécessaire de revoir la structure de la bdd, en particulier les clés primaires. Pour commencer, je propose de revoir conges_users (le plus important, je pense). 

Soit :  
- création d'un champ int auto-incrémenté en tant que clé primaire (u_login reste `unique`). 
- revoir clé étrangère dans les tables : conges_echange_rtt, conges_edition_papier, conges_groupe_grd_resp, onges_groupe_resp, conges_groupe_users, conges_periode, conges_solde_user, heure_additionnelle, heure_repos.

Reste a définir la procédure, j'hésite encore entre : 
- modifier (alter) la bdd en direct.
- dupliquer les données vers des nouvelles tables puis, a terme, dégager les anciennes au profit des nouvelles

**Comment by Prytoegrian** [comment]
Dupliquer la table est aller au devant d'ennui à mon sens :
- ça implique de reprendre une bonne partie du code, donc de le tester et serrer les fesses pour qu'il y ai aucun bug
- la duplication des données et la synchronisation peuvent être un enfer

À l'inverse, faire un alter table est potentiellement dangereux, mais :
- c'est pour cette raison que nous avons mis en place la sauvegarde
- il y a rien de sournois. Si ça pète, ça pète rapidement et fort
- puisque la synchronisation des clé étrangères est applicative, il "suffit" de toucher conges_users pour que tout fonctionne

Aussi, pour ma part je pencherais pour la seconde option. C'est pas facile, mais ça se fait. 
- nous pouvons ajouter un champ temporairement transparent pour le reste de l'application (la pk id)

**Comment by Prytoegrian** [comment]
Je place là ce que j'avais déjà trouvé, pour vider mes bookmarks. Si quelqu'un se sent d'humeur joueuse avant moi, qu'il se fasse plaisir :

https://stackoverflow.com/questions/9070764/insert-auto-increment-primary-key-to-existing-table
https://stackoverflow.com/questions/2341576/updating-mysql-primary-key
https://stackoverflow.com/questions/15255304/how-add-unique-key-to-existing-table-with-non-uniques-rows#15256049

**Comment by wouldsmina** [comment]
les requêtes sont prêtes, il me reste à modifier le code source...

**Comment by wouldsmina** [comment]
je me suis un peu cassé les dents dessus, je me sens pas de le refaire. Tu reprends le flambeau @prytoegrian ? Si tu peux le faire sur la table `conges_jours_feries` n'hésite pas, c'est plus prudent :smile:

**Comment by prytoegrian** [comment]
Ok, je tente.

**Comment by prytoegrian** [comment]
C'est quelque chose qui doit être fait côté /web en fait. J'ai fini, je fais encore des essais.
