### ISSUE TITLE
Suggestion de nommage suffixe table base de données

### ISSUE THREAD

**Issue by tneullas** [libertempo/api#4]
Actuellement libertempo utilise des tables ayant pour suffixe "conges_"
Les tables développées pour la 1.8 et la 1.9 n'ont pas de suffixe.

Personnellement je trouve cela pratique d'avoir un suffixe pour retrouver les bonnes tables lorsque plusieurs logiciels sont installer sur une même base (ce qui peut arriver souvent chez certains hébergeurs)

On pourrait envisager un suffixe plus court comme "lt_"

**Comment by Prytoegrian** [comment]
Je n'aime pas la pratique d'avoir un `préfixe`, vraiment pas. Malgré tout, si c'est une nécessité parce que certains ~~ne savent pas…~~ mettent tout dans la même base, on peut se poser la question.

Du coup, tout ce qu'on peut faire pour le moment compte tenu de la nature critique de la BDD, c'est une déclaration d'intérêt. À chaque fois qu'on ajoute un module dans l'API et qu'il devient le seul point d'entrée de la donnée, on pourra changer le nom de la table.

**Comment by tneullas** [comment]
C'est quoi une déclaration d'intérêt ?
Quels sont les raisons qui font que tu n'aimes pas les préfixes ?

Concernant plusieurs tables dans une même base ça vient des limitations de certains hébergeurs.
Parfois l'offre de base contient seulement une base de données avec un nombre de tables illimités.

La plupart des logiciels proposent cette option à l'installation si vraiment c'est un problème

**Comment by Prytoegrian** [comment]
Un déclaration d'intérêt serait un truc du genre (si on est pour) : « *on est ok, mais c'est un ticket qui se fera au long cours, au fur et à mesure des portages* ».

Je n'aime pas les préfixes car il ne font que répéter de l'information, elle ne sert donc à rien. À vouloir mettre des préfixes, tu te retrouves à préfixer tes tables, tes colonnes, etc. 
Sans que tu t'en rendes compte, si tu remets pas en cause ta convention, tu vas finir avec : 
* db : conges
  * table : conges_users
    * colonne : conges_users_id
    * colonne : conges_users_statut
    * colonne : conges_users_nom
    * …


Ceci étant, bien que ce soit une mauvaise pratique (entièrement de la responsabilité des hébergeurs), je comprends le besoin.

**Comment by wouldsmina** [comment]
je suis du même avis que @Prytoegrian. C'est une grosse erreur que de mélanger différentes informations dans une même bdd. Si une des appli contient une faille permettant de dumper la bdd, ça risque de faire très mal (d'ailleurs que dit la CNIL à ce sujet?).

Mais il est vrai que la plupart des hébergeurs gratuit propose une seul base de donnée, on doit prendre en compte cette subtilité comme on l'a fait pour fetch_all...

`lt_` me plaît bien, par contre, uniquement pour les tables le préfixe, sinon ça devient trop lourd...

**Comment by wouldsmina** [comment]
tiens! je viens seulement de remarquer que ce ticket était sur lt-api. C'est volontaire?

**Comment by tneullas** [comment]
Je suis d'accord que les préfixes doivent être uniquement sur le nom des tables.
Je n'aime pas non plus en avoir dans les colonnes c'est redondant.

Je ne l'ai pas mis sur LT Web car ça ne concerne pas vraiment la vue et c'est surtout un truc à réfléchir pour la nouvelle BDD.

**Comment by wouldsmina** [comment]
je travail sur #21 et je me demande si ce ne serait pas l'occasion de retirer les préfixes des tables, au moins celle impacté par #21...

**Comment by prytoegrian** [comment]
Nous gardons ça en tête, mais ça mérite pas forcément de conserver le ticket ouvert.
